# -*- coding: utf-8 -*-
"""Movie-recommendation-system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dp2scbRvveVt7fqx-5sXBv6I3aUN2vJe
"""

import numpy as np
import pandas as pd

movies=pd.read_csv('/content/tmdb_5000_movies.csv')
credits=pd.read_csv('/content/tmdb_5000_credits.csv')

movies.head()

credits.head()

movies=movies.merge(credits,on='title')

movies.head()

#genres
#id
#keywords
#title
#cast
#crew
#overview

movies=movies[['genres','id','keywords','title','cast','crew','overview']]

movies.head()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres

import ast
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

movies['genres']=movies['genres'].apply(convert)

movies.head()

movies['keywords']=movies['keywords'].apply(convert)

movies.head()

def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter != 3:
      L.append(i['name'])
      counter += 1
    else:
      break
  return L

movies['cast']=movies['cast'].apply(convert3)

movies.head()

def convert4(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

movies['crew']=movies['crew'].apply(convert4)

movies['overview'] = movies['overview'].apply(lambda x:x.split())

movies.head()

movies['overview'][0]

movies.head()

movies['genres']=movies['genres'].apply(lambda x: [i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x: [i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x: [i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x: [i.replace(" ","") for i in x])

movies.head()

movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

movies.head()

new_df=movies[['id','title','tags']]

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

new_df['tags'][0]

new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

new_df.head()

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

vectors=cv.fit_transform(new_df['tags']).toarray()

vectors.shape

cv

!pip install nltk

import nltk

from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

new_df['tags']=new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)

similarity[1]

def recommend(movie):
  movie_index=new_df[new_df['title'] == movie].index[0]
  distances=similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x: x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Batman')